export function runtimeCliHelp(): string {
  return [
    "king-ai gui commands:",
    "  king-ai inbox",
    "  king-ai messages <conversationId> [--tail n]",
    "  king-ai glance <conversationId>",
    "  king-ai agents [spawn|destroy]",
    "  king-ai roster",
    "  king-ai participants",
    "  king-ai preamble [--agent agent-id] [--reason wake|agenda] [--run run-id]",
    "  king-ai contacts [query]",
    "  king-ai whoami",
    "  king-ai reply <conversationId> <text>",
    "  king-ai send <agentId> <message> [--steer] [--type message|decision|blocker]",
    "  king-ai recv [--agent agent-id]",
    "  king-ai recall <query> [--limit n] [--conversation <id>]",
    "  king-ai escalate <message>",
    "  king-ai status",
    "  king-ai state export|import|reset",
    "  king-ai observe [--json] [--classification productive|idle|blocked|backlog_stuck|error]",
    "  king-ai loop tick|emit|classify|recent|snapshot [--json] [--type eventType] [--agent agent-id]",
    "  king-ai task create|list|get|update|done [--after a,b] [--path a,b] [--assign agent-id]",
    "  king-ai initiative create|list|get|update|advance|persist [--goal text] [--status active|paused|completed|abandoned]",
    "  king-ai initiative advance <id> [--dry-run] [--auto] [--apply '<json plan>'] [--assign agent-id]",
    "  king-ai initiative persist [--initiative id] [--create] [--title text] [--goal text]",
    "  king-ai capsule create|list|mine|get|update [--paths a,b] [--owner agent-id] [--reviewer agent-id]",
    "  king-ai merge enqueue|list|get|mark [--capsule id] [--task id] [--branch name]",
    "  king-ai eval parse|record|list|get '<json evaluation>' [--artifact id] [--initiative id]",
    "  king-ai feedback record|list|summary|get [--agent agent-id] [--completed true|false]",
    "  king-ai review record|list|get [--capsule id] [--coverage pct] [--checks true|false]",
    "  king-ai route set|list|delete|emit <eventType> [--agent agent-id] [--source source] '<payload json>'",
    "  king-ai card list|create|claim|move|done|release [--paths a,b] [--owner agent-id]",
    "  king-ai calendar list|create|delete <id>",
    "  king-ai claim <name> [--in <conversationId>] [--paths a,b] [--owner agent-id]",
    "  king-ai unclaim <claimId>",
    "  king-ai dm <agentId> <text>",
    "  king-ai react <messageId> <emoji>",
    "  king-ai doc list|create|show|append|update",
    "  king-ai artifact put|list|get|check --kind <kind> --path <path> --source <source> --confidence <0-1>",
    "  king-ai context get|set|list|delete <key> [value]",
    "  king-ai hypothesis create|list|update [--status <status>] [--evidence artifact-ids]",
    "  king-ai plan parse|apply '<json plan>' [--assign agent-id] [--initiative id]",
    "  king-ai safety check|request|list|get|approve|deny <action|approvalId>"
  ].join("\n");
}
